import json
import re
from typing import AsyncIterator, Dict, Optional
from urllib.parse import urlparse

import httpx

from app.core.config import settings
from app.core.exceptions import IPFSException, ValidationException
from app.storage.base import StorageAdapter

# CID regex specifications:
# CIDv0: 46-character Base58btc string starting with Qm
CID_V0_PATTERN = re.compile(r"^Qm[1-9A-HJ-NP-Za-km-z]{44}$")
# CIDv1: Base32 lowercase string starting with baf (typically bafy... for dag-pb)
CID_V1_PATTERN = re.compile(r"^baf[a-z2-7]{50,}$")


def is_valid_ipfs_cid(cid: str) -> bool:
    """
    Validates whether a string is a well-formed IPFS CID (CIDv0 or CIDv1).
    Prevents parameter injection and malicious path traversal in IPFS RPC calls.
    """
    if not cid or not isinstance(cid, str):
        return False
    clean = cid.strip()
    return bool(CID_V0_PATTERN.match(clean) or CID_V1_PATTERN.match(clean))


class IPFSStorageAdapter(StorageAdapter):
    """
    Decentralized storage adapter connecting to local IPFS Kubo RPC API (/api/v0/*).
    Supports single artifact pinning, multi-artifact directory DAG creation,
    content retrieval, pin management, and streaming verification.
    """

    def __init__(
        self,
        api_url: Optional[str] = None,
        gateway_url: Optional[str] = None,
        timeout_seconds: Optional[int] = None,
        transport: Optional[httpx.AsyncBaseTransport] = None,
    ) -> None:
        self._api_url = (api_url or settings.IPFS_API_URL).rstrip("/")
        self._gateway_url = (gateway_url or settings.IPFS_GATEWAY_URL).rstrip("/")
        self._timeout = timeout_seconds or settings.IPFS_TIMEOUT_SECONDS
        self._transport = transport

        # SSRF / URL validation guard
        parsed = urlparse(self._api_url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            raise ValueError(
                f"Invalid IPFS_API_URL: '{self._api_url}'. Must be a valid HTTP/HTTPS URL."
            )

        # In-memory buffer for active streaming chunk uploads keyed by storage_key
        self._buffers: Dict[str, bytearray] = {}
        # Mapping from storage_key to resolved IPFS CID
        self._key_to_cid: Dict[str, str] = {}

    def _create_client(self) -> httpx.AsyncClient:
        """Instantiates an AsyncClient configured with timeout and optional custom transport."""
        return httpx.AsyncClient(timeout=self._timeout, transport=self._transport)

    @property
    def api_url(self) -> str:
        return self._api_url

    @property
    def gateway_url(self) -> str:
        return self._gateway_url

    @property
    def timeout_seconds(self) -> int:
        return self._timeout

    def _validate_cid_arg(self, cid_or_path: str) -> str:
        """Sanitizes and validates CID parameter before sending to Kubo API."""
        if not cid_or_path:
            raise ValidationException(
                code="INVALID_CID",
                message="IPFS CID must not be empty.",
            )
        clean = cid_or_path.strip()
        root_cid = clean.split("/")[0]
        if not is_valid_ipfs_cid(root_cid):
            raise ValidationException(
                code="INVALID_CID_FORMAT",
                message=f"Invalid IPFS CID format: '{cid_or_path}'. Expected CIDv0 (Qm...) or CIDv1 (bafy...).",
                details={"cid": cid_or_path},
            )
        return clean

    # =========================================================================
    # CORE IPFS OPERATIONS
    # =========================================================================

    async def add_bytes(
        self, data: bytes, filename: Optional[str] = None, pin: bool = True
    ) -> str:
        """
        Uploads raw artifact bytes to the IPFS node via Kubo /api/v0/add.
        Returns the genuine CID generated by IPFS.
        """
        if not data:
            raise ValidationException(
                code="EMPTY_CONTENT_NOT_ALLOWED",
                message="Cannot upload empty (0-byte) content to IPFS.",
                details={"bytes": 0},
            )

        url = f"{self._api_url}/api/v0/add"
        params = {
            "pin": "true" if pin else "false",
            "cid-version": "1",
        }
        files = {"file": (filename or "artifact", data, "application/octet-stream")}

        try:
            async with self._create_client() as client:
                res = await client.post(url, params=params, files=files)
        except httpx.ConnectError as e:
            raise IPFSException(
                code="IPFS_CONNECTION_ERROR",
                message=f"Failed to connect to IPFS Kubo node at '{self._api_url}'. Ensure the IPFS daemon is active.",
                details={"api_url": self._api_url, "error": str(e)},
            )
        except httpx.TimeoutException as e:
            raise IPFSException(
                code="IPFS_TIMEOUT",
                message=f"IPFS request timed out after {self._timeout} seconds.",
                details={"api_url": self._api_url, "timeout": self._timeout},
            )
        except httpx.RequestError as e:
            raise IPFSException(
                code="IPFS_REQUEST_ERROR",
                message=f"IPFS HTTP request failed: {str(e)}",
                details={"error": str(e)},
            )

        if res.status_code != 200:
            raise IPFSException(
                code="IPFS_API_ERROR",
                message=f"IPFS node returned HTTP {res.status_code}: {res.text}",
                status_code=502,
                details={"status_code": res.status_code, "response": res.text},
            )

        # Parse response JSON
        try:
            body = res.json()
            cid = body.get("Hash")
        except Exception:
            # Handle ndjson if Kubo returns newline-delimited stream
            lines = [line.strip() for line in res.text.strip().split("\n") if line.strip()]
            if lines:
                body = json.loads(lines[-1])
                cid = body.get("Hash")
            else:
                cid = None

        if not cid or not is_valid_ipfs_cid(cid):
            raise IPFSException(
                code="IPFS_INVALID_RESPONSE",
                message="IPFS node did not return a valid CID.",
                details={"response": res.text},
            )

        return cid

    async def add_directory(
        self, files: Dict[str, bytes], pin: bool = True
    ) -> Dict[str, str]:
        """
        Uploads multiple named artifacts wrapped in an IPFS directory DAG.
        Conforms to BLOCKCHAIN_DESIGN.md Project Version root CID requirement.
        Returns a dictionary mapping:
        - filename -> individual artifact CID
        - "root" -> root directory DAG CID (ipfs_root_cid)
        """
        if not files:
            raise ValidationException(
                code="EMPTY_DIRECTORY_NOT_ALLOWED",
                message="Cannot create an IPFS directory DAG without files.",
            )

        url = f"{self._api_url}/api/v0/add"
        params = {
            "wrap-with-directory": "true",
            "pin": "true" if pin else "false",
            "cid-version": "1",
        }

        # Multi-file multipart payload
        files_payload = [
            ("file", (name, content, "application/octet-stream"))
            for name, content in files.items()
        ]

        try:
            async with self._create_client() as client:
                res = await client.post(url, params=params, files=files_payload)
        except httpx.ConnectError as e:
            raise IPFSException(
                code="IPFS_CONNECTION_ERROR",
                message=f"Failed to connect to IPFS Kubo node at '{self._api_url}'.",
                details={"api_url": self._api_url, "error": str(e)},
            )
        except httpx.TimeoutException as e:
            raise IPFSException(
                code="IPFS_TIMEOUT",
                message=f"IPFS directory upload timed out after {self._timeout} seconds.",
                details={"timeout": self._timeout},
            )
        except httpx.RequestError as e:
            raise IPFSException(
                code="IPFS_REQUEST_ERROR",
                message=f"IPFS HTTP request failed: {str(e)}",
            )

        if res.status_code != 200:
            raise IPFSException(
                code="IPFS_API_ERROR",
                message=f"IPFS node returned HTTP {res.status_code}: {res.text}",
                status_code=502,
                details={"response": res.text},
            )

        # Parse ndjson output containing an entry per file and the root wrap directory
        cid_mapping: Dict[str, str] = {}
        root_cid: Optional[str] = None

        lines = [line.strip() for line in res.text.strip().split("\n") if line.strip()]
        for line in lines:
            entry = json.loads(line)
            name = entry.get("Name", "")
            h = entry.get("Hash")
            if not h or not is_valid_ipfs_cid(h):
                continue

            if not name or name == "" or name.startswith("wrap"):
                root_cid = h
                cid_mapping["root"] = h
                cid_mapping[""] = h
            else:
                cid_mapping[name] = h

        # If Kubo's last entry was the directory wrapper
        if not root_cid and lines:
            last_entry = json.loads(lines[-1])
            root_cid = last_entry.get("Hash")
            if root_cid:
                cid_mapping["root"] = root_cid
                cid_mapping[""] = root_cid

        if not root_cid:
            raise IPFSException(
                code="IPFS_ROOT_DAG_ERROR",
                message="IPFS node failed to generate a root directory DAG CID.",
                details={"response": res.text},
            )

        return cid_mapping

    async def cat(self, cid_or_path: str) -> bytes:
        """Retrieves raw content bytes from IPFS by CID or path."""
        valid_cid = self._validate_cid_arg(cid_or_path)
        url = f"{self._api_url}/api/v0/cat"

        try:
            async with self._create_client() as client:
                res = await client.post(url, params={"arg": valid_cid})
        except httpx.ConnectError as e:
            raise IPFSException(
                code="IPFS_CONNECTION_ERROR",
                message=f"Failed to connect to IPFS node at '{self._api_url}'.",
            )
        except httpx.TimeoutException:
            raise IPFSException(
                code="IPFS_TIMEOUT",
                message=f"IPFS cat timed out after {self._timeout}s.",
            )

        if res.status_code != 200:
            raise IPFSException(
                code="IPFS_CONTENT_NOT_FOUND" if res.status_code == 500 and "not found" in res.text.lower() else "IPFS_API_ERROR",
                message=f"Failed to retrieve content for CID '{cid_or_path}': {res.text}",
                status_code=404 if "not found" in res.text.lower() else 502,
                details={"cid": cid_or_path, "response": res.text},
            )

        return res.content

    async def cat_stream(
        self, cid_or_path: str, chunk_size: int = 65536
    ) -> AsyncIterator[bytes]:
        """Streams content bytes incrementally from IPFS."""
        valid_cid = self._validate_cid_arg(cid_or_path)
        url = f"{self._api_url}/api/v0/cat"

        try:
            async with self._create_client() as client:
                async with client.stream("POST", url, params={"arg": valid_cid}) as response:
                    if response.status_code != 200:
                        err_text = await response.aread()
                        raise IPFSException(
                            code="IPFS_API_ERROR",
                            message=f"IPFS streaming failed: {err_text.decode('utf-8', errors='ignore')}",
                        )
                    async for chunk in response.aiter_bytes(chunk_size=chunk_size):
                        yield chunk
        except httpx.ConnectError:
            raise IPFSException(
                code="IPFS_CONNECTION_ERROR",
                message=f"Failed to connect to IPFS node at '{self._api_url}'.",
            )
        except httpx.TimeoutException:
            raise IPFSException(
                code="IPFS_TIMEOUT",
                message=f"IPFS stream timed out.",
            )

    async def pin(self, cid: str) -> bool:
        """Pins content on the IPFS node to ensure persistence."""
        valid_cid = self._validate_cid_arg(cid)
        url = f"{self._api_url}/api/v0/pin/add"

        try:
            async with self._create_client() as client:
                res = await client.post(url, params={"arg": valid_cid})
        except httpx.ConnectError:
            raise IPFSException(code="IPFS_CONNECTION_ERROR", message="Cannot connect to IPFS.")

        if res.status_code != 200:
            raise IPFSException(
                code="IPFS_PIN_ERROR",
                message=f"Failed to pin CID '{cid}': {res.text}",
            )
        return True

    async def unpin(self, cid: str) -> bool:
        """Removes a pin for the specified CID."""
        valid_cid = self._validate_cid_arg(cid)
        url = f"{self._api_url}/api/v0/pin/rm"

        try:
            async with self._create_client() as client:
                res = await client.post(url, params={"arg": valid_cid})
        except httpx.ConnectError:
            raise IPFSException(code="IPFS_CONNECTION_ERROR", message="Cannot connect to IPFS.")

        # If already unpinned or successful
        return res.status_code == 200

    async def is_pinned(self, cid: str) -> bool:
        """Checks if a given CID is pinned locally."""
        valid_cid = self._validate_cid_arg(cid)
        url = f"{self._api_url}/api/v0/pin/ls"

        try:
            async with self._create_client() as client:
                res = await client.post(url, params={"arg": valid_cid})
        except httpx.ConnectError:
            return False

        if res.status_code == 200:
            try:
                keys = res.json().get("Keys", {})
                return valid_cid in keys
            except Exception:
                return False
        return False

    # =========================================================================
    # StorageAdapter INTERFACE IMPLEMENTATION
    # =========================================================================

    async def write_chunk(
        self, storage_key: str, chunk: bytes, is_first_chunk: bool = False
    ) -> None:
        """Buffers chunk in memory for the given storage_key."""
        if is_first_chunk or storage_key not in self._buffers:
            self._buffers[storage_key] = bytearray()
        self._buffers[storage_key].extend(chunk)

    async def retrieve(self, storage_key: str) -> bytes:
        """Retrieves content from memory buffer or IPFS if key is a CID."""
        if storage_key in self._buffers:
            return bytes(self._buffers[storage_key])
        if storage_key in self._key_to_cid:
            return await self.cat(self._key_to_cid[storage_key])
        if is_valid_ipfs_cid(storage_key):
            return await self.cat(storage_key)
        raise FileNotFoundError(f"Content not found for key '{storage_key}'.")

    async def retrieve_stream(
        self, storage_key: str, chunk_size: int = 65536
    ) -> AsyncIterator[bytes]:
        """Streams content from buffer or IPFS."""
        if storage_key in self._buffers:
            data = bytes(self._buffers[storage_key])
            for i in range(0, len(data), chunk_size):
                yield data[i : i + chunk_size]
            return

        cid = self._key_to_cid.get(storage_key, storage_key)
        if is_valid_ipfs_cid(cid):
            async for chunk in self.cat_stream(cid, chunk_size=chunk_size):
                yield chunk
            return

        raise FileNotFoundError(f"Content not found for key '{storage_key}'.")

    async def delete(self, storage_key: str) -> bool:
        """Cleans up memory buffer and unpins IPFS content if associated."""
        deleted = False
        if storage_key in self._buffers:
            del self._buffers[storage_key]
            deleted = True
        cid = self._key_to_cid.pop(storage_key, None)
        if cid:
            await self.unpin(cid)
            deleted = True
        elif is_valid_ipfs_cid(storage_key):
            deleted = await self.unpin(storage_key)
        return deleted

    async def exists(self, storage_key: str) -> bool:
        """Checks if content exists in active buffer or IPFS."""
        if storage_key in self._buffers:
            return True
        cid = self._key_to_cid.get(storage_key, storage_key)
        if is_valid_ipfs_cid(cid):
            return await self.is_pinned(cid)
        return False


# Global singleton instance management
_global_ipfs_adapter: Optional[IPFSStorageAdapter] = None


def get_ipfs_adapter() -> IPFSStorageAdapter:
    """Returns the active global IPFSStorageAdapter singleton."""
    global _global_ipfs_adapter
    if _global_ipfs_adapter is None:
        _global_ipfs_adapter = IPFSStorageAdapter()
    return _global_ipfs_adapter


def set_ipfs_adapter(adapter: Optional[IPFSStorageAdapter]) -> None:
    """Overrides the active global IPFSStorageAdapter (primarily for testing)."""
    global _global_ipfs_adapter
    _global_ipfs_adapter = adapter

