"""initial_domain_models

Revision ID: 2ae5d84c1a42
Revises: 
Create Date: 2026-09-01 12:11:15.482858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae5d84c1a42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=False),
    sa.Column('current_lifecycle_stage', sa.Enum('IDEA', 'DESIGN', 'PROTOTYPE', 'FINAL', name='project_version_stage'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'INSTITUTIONAL', 'PRIVATE', name='project_visibility'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'UNDER_DISPUTE', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_public_id'), 'projects', ['public_id'], unique=True)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'ADMIN', 'VERIFIER', name='user_role'), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('claimant_user_id', sa.UUID(), nullable=False),
    sa.Column('dispute_type', sa.Enum('PLAGIARISM', 'UNAUTHORIZED_USE', 'CITATION_FAILURE', 'OTHER', name='dispute_type'), nullable=False),
    sa.Column('claim_description', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('NONE', 'OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='dispute_status'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claimant_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_claimant_user_id'), 'disputes', ['claimant_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_project_id'), 'disputes', ['project_id'], unique=False)
    op.create_index(op.f('ix_disputes_public_id'), 'disputes', ['public_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('BLOCKCHAIN_CONFIRMATION', 'TEAM_INVITE', 'DISPUTE_ALERT', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_public_id'), 'notifications', ['public_id'], unique=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_project', sa.Enum('LEAD', 'CONTRIBUTOR', 'FACULTY_MENTOR', name='project_member_role'), nullable=False),
    sa.Column('contribution_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user_membership')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('version_index', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.Column('lifecycle_stage', sa.Enum('IDEA', 'DESIGN', 'PROTOTYPE', 'FINAL', name='project_version_stage'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('composite_sha256', sa.String(length=66), nullable=True),
    sa.Column('ipfs_root_cid', sa.String(length=255), nullable=True),
    sa.Column('anchoring_status', sa.Enum('DRAFT', 'PENDING', 'ANCHORING', 'ANCHORED', 'FAILED', name='anchoring_status'), nullable=False),
    sa.Column('dispute_status', sa.Enum('NONE', 'OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='dispute_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_index', name='uq_project_version_index')
    )
    op.create_index(op.f('ix_project_versions_idempotency_key'), 'project_versions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_versions_public_id'), 'project_versions', ['public_id'], unique=True)
    op.create_index(op.f('ix_project_versions_registration_id'), 'project_versions', ['registration_id'], unique=True)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('ipfs_cid', sa.String(length=255), nullable=False),
    sa.Column('artifact_category', sa.Enum('SOURCE_CODE', 'DOCUMENTATION', 'DESIGN_SPEC', 'PRESENTATION', 'OTHER', name='artifact_category'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_public_id'), 'artifacts', ['public_id'], unique=True)
    op.create_index(op.f('ix_artifacts_sha256_hash'), 'artifacts', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_artifacts_version_id'), 'artifacts', ['version_id'], unique=False)
    op.create_table('blockchain_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('onchain_record_id', sa.BigInteger(), nullable=True),
    sa.Column('smart_contract_address', sa.String(length=42), nullable=False),
    sa.Column('anchored_hash', sa.String(length=66), nullable=False),
    sa.Column('ipfs_cid_anchored', sa.String(length=255), nullable=False),
    sa.Column('submitter_wallet', sa.String(length=42), nullable=False),
    sa.Column('author_wallet', sa.String(length=42), nullable=False),
    sa.Column('network_name', sa.String(length=50), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('anchored_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_records_public_id'), 'blockchain_records', ['public_id'], unique=True)
    op.create_index(op.f('ix_blockchain_records_transaction_hash'), 'blockchain_records', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_blockchain_records_version_id'), 'blockchain_records', ['version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain_records_version_id'), table_name='blockchain_records')
    op.drop_index(op.f('ix_blockchain_records_transaction_hash'), table_name='blockchain_records')
    op.drop_index(op.f('ix_blockchain_records_public_id'), table_name='blockchain_records')
    op.drop_table('blockchain_records')
    op.drop_index(op.f('ix_artifacts_version_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_sha256_hash'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_public_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_project_versions_registration_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_public_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_idempotency_key'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_public_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_disputes_public_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_project_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_claimant_user_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_public_id'), table_name='projects')
    op.drop_table('projects')

    # Drop custom PostgreSQL enum types on downgrade
    for enum_name in [
        'project_version_stage',
        'project_visibility',
        'project_status',
        'user_role',
        'dispute_type',
        'dispute_status',
        'notification_type',
        'project_member_role',
        'anchoring_status',
        'artifact_category',
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE;")
    # ### end Alembic commands ###
