"""add_institution_name_to_users

Revision ID: 371b936ff5ba
Revises: 2ae5d84c1a42
Create Date: 2026-09-03 23:23:57.441451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371b936ff5ba'
down_revision: Union[str, None] = '2ae5d84c1a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'version_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('artifacts', 'ipfs_cid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('users', sa.Column('institution_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'institution_name')
    op.alter_column('artifacts', 'ipfs_cid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('artifacts', 'version_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
